---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

notifications: true
automerge: true
files:
  github/:
    supershipit: $team_admin
  plugins/:
    supershipit: $team_admin
  docs/:
    supershipit: $team_admin
  meta/:
    supershipit: $team_admin
  roles/:
    supershipit: $team_admin
  changelogs/:
    supershipit: $team_admin
  changelogs/fragments/:
    support: 3a2dev
  $github:
    labels: github
  $gitaction:
    labels: github_action
  $actions:
    labels: action
  $becomes/:
    labels: become
  $caches/:
    labels: cache
  $callbacks/:
    labels: callbacks
  $connections/:
    labels: connections
  $doc_fragments/:
    labels: docs_fragments
  $inventories/:
    labels: inventories
  $lookups/:
    labels: lookups
  $module_utils/:
    labels: module_utils
#########################
  docs/docsite/config.yml:
    maintainers: NomakCooper
  docs/docsite/extra-docs.yml:
    maintainers: NomakCooper
  docs/docsite/links.yml:
    maintainers: NomakCooper
  docs/docsite/rst/guide_dependencies.rst:
    maintainers: NomakCooper
  docs/docsite/rst/guide_install.rst:
    maintainers: NomakCooper
  docs/docsite/rst/guide_roles.rst:
    maintainers: NomakCooper
  docs/docsite/rst/role_guide_install_dep.rst:
    maintainers: NomakCooper
  docs/dosite/rst/role_guide_sar_filter.rst:
    maintainers: NomakCooper
#########################
  meta/ee-bindep.txt:
    maintainers: NomakCooper
  meta/ee-requirements.txt:
    maintainers: NomakCooper
  meta/execution-environment.yml:
    maintainers: NomakCooper
  meta/runtime.yml:
    maintainers: NomakCooper
#########################
  README.md:
    maintainers: NomakCooper
    supershipit: NomakCooper
  galaxy.yml:
    maintainers: NomakCooper
    supershipit: NomakCooper
#########################
  $modules/charts.py:
    maintainers: NomakCooper
  $modules/chrony_info.py:
    maintainers: NomakCooper
  $modules/exa_facts.py:
    maintainers: NomakCooper
  $modules/open_xl.py:
    maintainers: NomakCooper
  $modules/sar_facts.py:
    maintainers: NomakCooper
#########################
  tests/:
    labels: tests
    supershipit: NomakCooper
  tests/integration:
    labels: integration
    support: 3a2dev
  tests/unit/:
    labels: unit
    support: 3a2dev
  tests/utils/:
    labels: unit
    maintainers: NomakCooper
macros:
  actions: plugins/action
  becomes: plugins/become
  caches: plugins/cache
  callbacks: plugins/callback
  connections: plugins/connection
  doc_fragments: plugins/doc_fragments
  filters: plugins/filter
  inventories: plugins/inventory
  lookups: plugins/lookup
  module_utils: plugins/module_utils
  modules: plugins/modules
  plugin_utils: plugins/plugin_utils
  tests: plugins/test
  gitaction: .github/workflows
  github: .github
  team_ansible_core:
  team_admin: NomakCooper